### PR TITLE
merge with Axetroy's version

### PR DESCRIPTION
**Pull request by axetroy**
Prior to this, I spent a lot of time to complete a lot of work, including `test cases`/`automation CI` and son on.

I hope it can also be applied to the new version.

Eg. when you run `git push --tags`, CI will automatically bundle and publish to Github release page and VSCODE Market.

So @ry needs to set `secrets.GH_TOKEN` and `secrets.ADO_TOKEN`

`secrets.GH_TOKEN`: Github Token with Edit release page permission

截屏2020-05-0811 25 52

`secrets.ADO_TOKEN`:

Azure DevOps Personal Access Token

if you have use vsce before, you can get it with following command: `cat ~/.vsce` and get `pat` field.

NOTE: Azure DevOps Personal Access Token is valid for a maximum of one year, so it will expire after one year.

截屏2020-05-0811 11 02

Of course, if you need test coverage, you also need to set `secrets.COVERALLS_REPO_TOKEN` which is currently optional

截屏2020-05-0811 35 30

### CODE REVIEW

**Comment by axetroy** [comment]
You can download the new one from here https://github.com/denoland/vscode_deno/suites/663533308/artifacts/5873986

**Comment by justjavac** [comment]
Will this cover my code base?

**Comment by axetroy** [comment]
@justjavac Yes. it sure.

This branch based on your, I submitted hundreds of commits

If you need to re-implement step by step now, it is equivalent to repeating my past work again, and I won't do that

**Comment by justjavac** [comment]
After you fork my repo, I have continued to do a lot of work. Maybe I should check the time of your fork, let's talk in WeChat.

**Comment by ry** [comment]
@axetroy Cool - I will setup the GH_TOKEN. Thank you.

I'm just waiting to hear from @justjavac to make sure he's okay with merging in the fork. I haven't dived into this code myself, so I'm hoping you two can reach consensus.

**Comment by axetroy** [comment]
@ry 
Due to the excessive amount of code in this PR, it is difficult to review, I decided to close PR.

In the next time, it will be updated gradually by @justjavac

After all, there are already two available extensions in the vscode market

When the official version is released, I will remove the extension on the vscode market to prevent misleading users, Now, My branch is now marked as enabled `deprecated

**Comment by ry** [comment]
I'm not sure it needs to all be reviewed... If @justjavac wants to go through it carefully and merge it, I guess that would be preferable as it would increase code quality. But I would also be fine to just merge and go from there - from what I understand you've added many features. It's not clear to me how big the diff actually is?

**Comment by justjavac** [comment]
we have communicated privately, I will add these missing features

Some features only exist in his repo, such as deno-types, quick fix, etc., and some features only exist in my repo.

we use completely different code structures. If we combine the features of the two together, we can only use the way by copy-paste-modify.

**Comment by justjavac** [comment]
I will talk to him tomorrow, maybe we should merge his pr, and then I copy my code into it

**Pull request closed without merging**
