### PR TITLE
feat: enable via config file detection

### LINKED ISSUE #880: Auto-enable extension when deno.json/deno.jsonc is present
It'd be awesome if the extension could by default look for a deno.json or deno.jsonc file and if one of the two is available, set `deno.enable` automatically to `true`.

**Why?**

A lot of Deno projects (e.g. the std library) don't configure `deno.enable` for just the workspace, making it annoying for people who don't have  `deno.enable` set to `true` globally.

Also, this would allow us to have one file less in our codebases. :)

### PR DESCRIPTION
**Pull request by nayeemrmn**
Closes #880.
Needs https://github.com/denoland/deno/pull/20334.

### CODE REVIEW

**Comment by nayeemrmn** [comment]
https://github.com/denoland/vscode_deno/assets/29990554/36a1d263-2487-4316-87a7-3de417635d42

**Review by bartlomieju — COMMENTED** [review]
Is this change backwards compatible? Ie. after landing and releasing extension will older versions of Deno (<= 1.36.x) still work?

**Comment by nayeemrmn** [comment]
> Is this change backwards compatible? Ie. after landing and releasing extension will older versions of Deno (<= 1.36.x) still work?

The protocol is. However, with a new extension version; an old Deno version; `deno.enable` unspecified and `deno.json` in the directory, both the Deno and Node/TS language servers will be inactive. We expect such users to have had `deno.enable: true` set though. So rare edgecase with not so bad behaviour.

**Comment by nayeemrmn** [comment]
Actually wait, I checked and there is a problem with null not being accepted for `enable` for an old lsp version. I thought the `#[serde(default)]` above it handled that...

**Comment by nayeemrmn** [comment]
Okay it's because https://github.com/denoland/deno/blob/9d58c896dc11be39727729b74ebe5d5d7bb58767/cli/lsp/config.rs#L239 doesn't have a `#[serde(default)]` above it like https://github.com/denoland/deno/blob/9d58c896dc11be39727729b74ebe5d5d7bb58767/cli/lsp/config.rs#L292 does.

**Comment by bartlomieju** [comment]
Alright, so a new extension version will cause problems? Maybe we can make this feature conditional depending on the Deno binary version and only use it for >= v1.37?

**Review by bartlomieju — APPROVED** [review]
LGTM 🚀

**Comment by nayeemrmn** [comment]
> Alright, so a new extension version will cause problems? Maybe we can make this feature conditional depending on the Deno binary version and only use it for >= v1.37?

Done. For anyone that wants to play around with it, remove the check from https://github.com/denoland/vscode_deno/pull/902/commits/b6a0d19ca12f0439e12d3387de61d7d693431697.

**Pull request merged**
