### PR TITLE
fix: do not cache unsupported origins in config

### PR DESCRIPTION
**Pull request by kitsonk**
Ref: denoland/deno#12621

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
I feel like we might want to save the "No" when the user explicitly opts out by pressing "No". If they cancel though, we should do nothing. That way we won't prompt the user again about a specific registry once we eventually get around to re-fetching the manifest every 24 hours (the old extension did this).

**Comment by kitsonk** [comment]
@lucacasonato you are right... good catch, I will amend.

**Comment by kitsonk** [comment]
Actually that is what it does.  If you say `"No"` (specifically not `"Enable"`) it will set that origin as `false` instead of `true`, so it follows the behaviour you describe.

And denoland/deno#9931 should address the reloading of not found origins daily.

**Review by lucacasonato — APPROVED** [review]
Must have misread then. LGTM!

**Pull request merged**
