### PR TITLE
Add init project command to quickly get things setup

### PR DESCRIPTION
**Pull request by CGQAQ**
pr1

### CODE REVIEW

**Comment by CGQAQ** [comment]
@lucacasonato sorry, mb

**Review by lucacasonato — COMMENTED** [review]
This is looking good. Can you make the flow be like this:

1. User runs `Deno: Init` command
2. Question: `Enable --unstable?` (the user can answer `yes` or `no`)
3. If --unstable: Question: `Enable deno lint?` (the user can answer `yes` or `no`)

**Comment by CGQAQ** [comment]
> If --unstable: Question: Enable deno lint? (the user can answer yes or no)

I think let user choose unstable is unnecessary, you you turn on a feature need unstable, just turn on unstable as well, otherwise just keep it off

**Comment by lucacasonato** [comment]
> I think let user choose unstable is unnecessary, you you turn on a feature need unstable, just turn on unstable as well, otherwise just keep it off

Right, I just want to make users aware that there is a `unstable` option. So what about this:

1. User runs Deno: Init command
2. Question: Enable deno lint? (the user can answer yes or no)
3. Write config file and print message:
```
Deno is now set up. You can enable and disable settings (like `--unstable`) in the `.vscode/settings.json` file. Before the extension will work you need to restart VS Code.

[Restart VS Code]
```

When the user presses `[Restart VS Code]` the window should be reloaded.

**Comment by CGQAQ** [comment]
@lucacasonato don't need to restart, just `reload window` is enough, I'll look for how to add a button to message

**Comment by CGQAQ** [comment]
image
@lucacasonato ready for review....again

**Review by lucacasonato — APPROVED** [review]
LGTM - thanks

**Pull request merged**
