### PR TITLE
support deno lint

### LINKED ISSUE #116: Add Linter support.
It would be great to have the linter "baked-in", the same way the formatter works, this is:

- Show problems in the Problems tab
- Show problems directly in the source code

I understand that lint functionality is unstable. However, there is no reason to not implement this, and add a note.

### PR DESCRIPTION
**Pull request by axetroy**
close #116 

Please wait for these two issues to be resolved before merging

- [x] https://github.com/denoland/deno/issues/7218
- [x] https://github.com/denoland/deno_lint/issues/290
- [x] Deno 1.3.3 release which will contain these features

### CODE REVIEW

**Comment by lucacasonato** [comment]
@axetroy #7303 has landed in Deno, so all required features should now be available on master. The 1.3.3 release on Friday will contain these features.

**Comment by bartlomieju** [comment]
Just a note - line numbers are still 1-based.

**Comment by lucacasonato** [comment]
@axetroy 1.3.3 has been released with all required features.

**Comment by axetroy** [comment]
notable change:

1. The minimum version number supports v1.3.3 of Deno. A warning will be issued if it is lower than the minor version

2. To use `lint`, you need to enable `deno.unstable = true` and `deno.lint = true`

**Comment by axetroy** [comment]
/cc @lucacasonato @bartlomieju all ready for review

Since my mother tongue is not English, So if some English descriptions are not accurate, please correct me.

**Comment by bartlomieju** [comment]
> 1. // deno-lint-ignore-next-line [rule]

We don't support this directive 

> 2. // deno-lint-ignore-file
> 3. ~// deno-lint-ignore [rule]~ not yet.

But we support these two

**Comment by axetroy** [comment]
> > 1. // deno-lint-ignore-next-line [rule]
> 
> We don't support this directive
> 
> > 1. // deno-lint-ignore-file
> > 2. ~// deno-lint-ignore [rule]~ not yet.
> 
> But we support these two

Is there something wrong? `// deno-lint-ignore-next-line [rule]` did works in v1.3.3 although I did not see the information of `deno help lint`

**Comment by bartlomieju** [comment]
> > > 1. // deno-lint-ignore-next-line [rule]
> > 
> > 
> > We don't support this directive
> > > 1. // deno-lint-ignore-file
> > > 2. ~// deno-lint-ignore [rule]~ not yet.
> > 
> > 
> > But we support these two
> 
> Is there something wrong? `// deno-lint-ignore-next-line [rule]` did works in v1.3.3 although I did not see the information of `deno help lint`

Then it seems to be a bug in implementation... 😢  currently `deno lint` uses following directives:
```rust
fn create_linter(syntax: Syntax, rules: Vec<Box<dyn LintRule>>) -> Linter {
  LinterBuilder::default()
    .ignore_file_directives(vec!["deno-lint-ignore-file"]) <--- ignore whole file
    .ignore_diagnostic_directives(vec![
      "deno-lint-ignore",                             <---- ignore certain diagnostic 
      "eslint-disable-next-line",                 <---- ignore certain diagnostic (compatibility with ESLint)
    ])
    .lint_unused_ignore_directives(true)
    // TODO(bartlomieju): switch to true
    .lint_unknown_rules(false)
    .syntax(syntax)
    .rules(rules)
    .build()
}
```

I'll try to fix this problem soon, but @axetroy please don't add `deno-lint-ignore-next-line` - I don't intend to support this directive.

**Comment by axetroy** [comment]
@bartlomieju update.

BTW. I think `deno-lint-ignore-next-line` is necessary.

`// deno-lint-ignore [rule]` should ignore the rule in the file.
`// deno-lint-ignore-next-line [rule]` only ignore the error in the next line.

**Comment by bartlomieju** [comment]
> `// deno-lint-ignore-next-line [rule]` only ignore the error in the next line.

That's what `deno-lint-ignore` does - it only applies to the next line. I think that `-next-line` is superfluous.

**Comment by axetroy** [comment]
> > `// deno-lint-ignore-next-line [rule]` only ignore the error in the next line.
> 
> That's what `deno-lint-ignore` does - it only applies to the next line. I think that `-next-line` is superfluous.

So, what if I want to ignore a type of error in the file? To ignore all of them, I have to add `// deno-lint-ignore-next-line [rule]` in every line. This is unfriendly for development.

**Comment by bartlomieju** [comment]
@axetroy we can add rule codes to `deno-lint-ignore-file [codes...]`

**Review by lucacasonato — COMMENTED** [review]
This is looking very promising. There are a few issues I found while testing:

- the `ignore next line rule` quickfix does not work. It gives the error `command 'deno._ignore_text_line_hint' not found`.
- As the source of the error, `Deno Language Server` is shown in the popover. It would be nice if this said `deno_lint` instead. So the error shown would be `Empty switch statement deno_lint(no-empty)`. If this is not possible `Empty switch statement Deno(lint/no-empty)` would be good too.

**Comment by axetroy** [comment]
@lucacasonato 
> the ignore next line rule quickfix does not work. It gives the error command 'deno._ignore_text_line_hint' not found.

This is a typo and have been fixed. https://github.com/denoland/vscode_deno/pull/162/commits/0de60e6e4048c9df0d7ff76efe1b463aeda7f09e
 
> As the source of the error, Deno Language Server is shown in the popover. It would be nice if this said deno_lint instead. So the error shown would be Empty switch statement deno_lint(no-empty). If this is not possible Empty switch statement Deno(lint/no-empty) would be good too.

Not `Deno Language Server` >>> `deno_lint` https://github.com/denoland/vscode_deno/pull/162/commits/98bd0ec01fef5829bfdf963b7eb713b3723ea5f3

**Comment by axetroy** [comment]
@lucacasonato 
rename `Deno Language Server` to `deno_lint` seem to get a problem.  wait for a minute and I am trying.

**Comment by axetroy** [comment]
@lucacasonato rename `Deno Language Server` to `deno_lint` done

**Review by lucacasonato — APPROVED** [review]
Thanks @axetroy! This is a great feature to have - I will create a 2.2 release for this feature today.

**Pull request merged**
