### PR TITLE
Add enable disable command

### LINKED ISSUE #170: [regression] deno enable/disable command palette entries removed
There is no longer a VS Code command palette option to "Enable Deno" or to "Disable Deno" (it seems I must manually create the workspace settings file in every new workspace).

**Screenshots**

vscode-command-palette-deno

**Versions**

vscode: `1.48.2`
deno: `1.3.2`
extension: `2.0.16`

### PR DESCRIPTION
**Pull request by CGQAQ**
Depends on #196, Please review it first

Show `enable command` when lsp is disabled, `disable command` when lsp is enabled

pr3

pr

Part of roadmap 2 (#194)

Closes #170

### CODE REVIEW

**Comment by CGQAQ** [comment]
@bartlomieju @axetroy @lucacasonato  Ready for review

**Comment by David-Else** [comment]
I remember this addition was debated before in the old extension and removed. I like the idea, but my only reservation is that now there are more options, logically they should be togglable as well? Perhaps instead `Init Deno project` creates and opens:

```
// .vscode/settings.json
{
  "deno.enable": true,
  "deno.unstable": true,
  "deno.lint": true,
}
```
This could be a nice time-saver? It would force people to make decisions on these options right away, and educate them that they exist.

**Comment by CGQAQ** [comment]
I think to add every config to command is not a good idea

**Comment by axetroy** [comment]
> I think to add every config to command is not a good idea

as I said. https://github.com/denoland/vscode_deno/issues/170#issuecomment-687553557

Consider adding a `deno.init` command for configuration, every field.

**Comment by CGQAQ** [comment]
Don't need anymore

**Pull request closed without merging**
